### ISSUE TITLE
troubleshooting

### ISSUE THREAD

**Issue by rdbartlett** [wow13524/invite-role-bot#2] opened 2022-09-28 08:13 UTC
Hi @wow13524, thanks for making this awesome bot! I have used it successfully in the past, but I needed it again today and it is not working. Is it ok if I ask you here for some support in troubleshooting?

**Comment by wow13524** [comment] 2022-10-02 04:38
Can you clarify what's not working correctly?

**Comment by aholtzmann** [comment] 2022-10-05 21:26
Confirming this issue report - the bot accepts configuration via slash commands but does not seem to be able to assign the roles when the invitation codes are used.

I have confirmed the Invite-Role Bot role is above the roles in question/use.

It may occur on first join for some reason - roles are being assigned to my test account, but that did not happen on my first attempt.

**Comment by wow13524** [comment] 2022-10-06 02:43
@aholtzmann This was previously reported in #3 which has since been resolved.  I am unable to reproduce this behavior with newly created invites.

**Comment by aholtzmann** [comment] 2022-10-06 02:49
In my testing it wasn't a newly created invite, it was an invite that had been used but my test account was new. I created my test account today and it was ignored until I tried our other invite (which was still brand new).

**Comment by wow13524** [comment] 2022-10-06 06:45
> In my testing it wasn't a newly created invite, it was an invite that had been used but my test account was new. I created my test account today and it was ignored until I tried our other invite (which was still brand new).

@aholtzmann Can you detail this in a new issue and provide steps to reproduce this behavior?  Thanks.

**Comment by aholtzmann** [comment] 2022-11-09 20:53
Unable to recreate - going to assume the issue was caused by spam protection timing. Thanks for the great 'bot.

**Closed as completed** 2022-11-09 21:26 UTC
